services:
  # this is the Twingate connector that allows access into the Render private network.
  - type: worker
    name: twingate-connector
    branch: main
    env: docker
    autoDeploy: false
    dockerfilePath: ./twingate/Dockerfile
    dockerContext: ./twingate
    envVars:
      - key: TENANT_URL
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: REFRESH_TOKEN
        sync: false
      - key: TWINGATE_LOG_ANALYTICS
        value: "v1"
      - key: TWINGATE_LABEL_DEPLOYEDBY
        value: "render"
